# Generated by Django 5.1.3 on 2024-11-29 08:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('nationality', models.CharField(max_length=255, verbose_name='Nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, unique=True, verbose_name='Model')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
                ('display_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Display Size')),
                ('is_available', models.BooleanField(default=False, verbose_name='Is Available')),
                ('made_in', models.CharField(max_length=255, verbose_name='Made In')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='main.brand', verbose_name='Brand')),
            ],
        ),
    ]
