# Generated by Django 5.1.3 on 2024-11-29 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_phone_display_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='display_size',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Display Size'),
        ),
    ]
