# Generated by Django 5.1.3 on 2024-11-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_brand_name_alter_brand_nationality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Phone', 'verbose_name_plural': 'Phones'},
        ),
    ]
